# docker-compose.yml

services:
  audit-log-srv:
    build: ./audit-log-srv
    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./audit-log-srv:/app
      - ./shared_logs:/var/log
    networks:
      - app-network

  company-srv:
    build: ./company-srv
    ports:
      - "8001:8000"

    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./company-srv:/app
      - ./shared_logs:/var/log
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres     # Default username (optional)
      POSTGRES_PASSWORD: password # Required superuser password
      POSTGRES_DB: mydatabase     # Initial database to create (optional)
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
