# docker-compose.yml
version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - audit-log-ms
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  audit-log-ms:
    build: ./audit-log-ms
    ports:
      - "8000:8000"
    environment:
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - db
    volumes:
      - ./audit-log-ms:/app
    networks:
      - app-network
      - vault-network

  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
  vault-network:
    external: true