[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "company-srv"
version = "0.1.0"
description = "Company Service"
requires-python = ">=3.8"

[tool.pytest.ini_options]
pythonpath = [
    "src"
]